# Generated by Django 2.0.7 on 2018-07-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obed_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='otherNames',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(max_length=35),
        ),
    ]
