# Generated by Django 2.0.7 on 2018-07-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obed_authentication', '0002_auto_20180729_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
