# Generated by Django 2.0.7 on 2018-07-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obed_authentication', '0003_auto_20180729_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
